### ISSUE TITLE
Add finch-tensor as a downstream CI test to Finch.jl

### ISSUE THREAD

**Issue by willow-ahrens** [finch-tensor/finch-jl-python#18]
I don't know how to do this but I think we probably should figure out how to run finch-tensor tests on Finch.jl PRs.

**Comment by mtsokol** [comment]
When I want to run `finch-tensor` tests with local `Finch.jl` repo I modify `src/finch/julia.py` line 3 in `finch-tensor` to:
```python
juliapkg.add("Finch", "9177782c-1635-4eb9-9bfb-d9dfa25e6bce", path="/Users/mateusz/JuliaProjects/Finch.jl", dev=True)
```
Which installs the local version.

One option how we can do this is to add a new CI job that installs Julia, checkout relevant `Finch.jl` branch (as it's done right now in existing jobs), then clones `finch-tensor`.

The "local" Finch.jl in `julia.py` could be selectable with an environment variable:

```python
if ENV_DEV_FINCH:
    juliapkg.add("Finch", "9177782c-1635-4eb9-9bfb-d9dfa25e6bce", path=PATH_TO_FINCH, dev=True)
else:
    juliapkg.add("Finch", "9177782c-1635-4eb9-9bfb-d9dfa25e6bce", version="0.6.14")
```

In a CI job we define `ENV_DEV_FINCH=true` and `PATH_TO_FINCH` variables (path given by github workflows I guess).

This way we can test each Finch.jl PR against `finch-tensor` `main` branch.

**Comment by willow-ahrens** [comment]
thanks mateusz! closed in https://github.com/willow-ahrens/Finch.jl/issues/535
