### ISSUE TITLE
Discrepancy in `%` operator

### ISSUE THREAD

**Issue by mtsokol** [finch-tensor/finch-jl-python#52]
I think that we still could match Python behavior in terms of `%` operator and negative input.
[Array API standard](https://data-apis.org/array-api/latest/API_specification/generated/array_api.remainder.html) describes several edge cases, and also says:

> In the remaining cases, the result must match that of the Python % operator.

And I think negative input falls into that rule. Therefore we could take a look at these differences:

Python
```python
In [113]: 2 % 10
Out[113]: 2

In [114]: -2 % 10
Out[114]: 8

In [115]: -2 % -10
Out[115]: -2

In [116]: 2 % -10
Out[116]: -8
```

Julia
```julia
julia> 2 % 10
2

julia> -2 % 10
-2

julia> -2 % -10
-2

julia> 2 % -10
2
```

**Comment by willow-ahrens** [comment]
did we just mix up `mod` and `rem` ? 

```
julia> rem(-2, 10)
-2

julia> mod(-2, 10)
8

julia> mod(2, 10)
2

julia> rem(2, 10)
2

julia> mod(2, -10)
-8

julia> mod(-2, -10)
-2

```

**Comment by willow-ahrens** [comment]
I think we just need to add mod_nothrow

**Comment by willow-ahrens** [comment]
fixed in https://github.com/willow-ahrens/finch-tensor/pull/56
