### ISSUE TITLE
`Storage` object comparison operator

### ISSUE THREAD

**Issue by hameerabbasi** [finch-tensor/finch-jl-python#67]
But we don't really have a string representation of a format or a format property in the `Tensor` class. So there's no way checking if the current format is e.g. `csf` and I would prefer to avoid parsing Julia's `_obj` repr if it matches some regex - it appears counterproductive to me.

_Originally posted by @mtsokol in https://github.com/willow-ahrens/finch-tensor/pull/45#discussion_r1629339973_

**Comment by willow-ahrens** [comment]
We could recursively walk the levels creating copies and error if we reach a level where the formats don't match. Even if we had a string format thing, we would still need to recurse down the levels to do the copy.

**Comment by willow-ahrens** [comment]
Perhaps `typeof` should suffice

**Comment by willow-ahrens** [comment]
I think this is a dup of https://github.com/willow-ahrens/finch-tensor/issues/13, and for now we can use typeof until we merge https://github.com/willow-ahrens/finch-tensor/pull/19
